### ISSUE TITLE
version conflicts

### ISSUE THREAD

**Issue by maoberlehner** [maoberlehnerdrupal/bower_manager#11]
We need to check how to resolve the versions. Is ~2.1 the same as 2.1.\* ... get them all to a form we can compare. Can we use [version_compare](http://php.net/manual/en/function.version-compare.php) here or do we need to implement our own compare function? Then we find the newest version, put that in bower.json and warn the user about what we did.

**Comment by maoberlehner** [comment]
I think we have to use something like this for reliable version detecting: https://github.com/vierbergenlars/php-semver

**Comment by hipnaba** [comment]
I like this. But how do we handle this dependency? Do we depend on Libraries or Composer Manager? Do you agree we need to resolve version conflicts between modules before merging?

**Comment by hipnaba** [comment]
Also. The package 'version' can also be in the form of an URL. What do we do in that case?

**Comment by maoberlehner** [comment]
I think composer is the "right way" to deal with dependencies in the modern PHP world so we definitely should support that way - the question is, do we make composer (Manager) mandatory (and add composer_manager as dependency) or do we provide a manual way to install dependencies?

personally i use Composer Manager no matter what, so I wouldn't mind to make it mandatory - but for some others it may be a deal breaker?

So I think our options are:
A) make composer_manager mandatory (most simple for us)
B) optionally support composer and provide a description in the README of how to manually download the dependencies (so we can't rely on the autoloading and have to implement logic to load the dependencies ourself)

I favor A

**Comment by maoberlehner** [comment]
I think URLs should trump regular versions - when I think about it, a typical case in which you use a URL is, if you want a very specific version of a package (e.g. a patched version or your own custom version) so i think it makes sense, that URLs trump versions.

Of course there are other reasons to use a URL so it is definitely not a perfect solution - but again, I think there is no perfect solution.

**Comment by hipnaba** [comment]
I agree there's no perfect solution but I think we should try to resolve as
much as we can ourselves. I'm definitely for warning a user there has been
a conflict, it's resolved but he should check up on it.

what if we have 2 urls? i.e. ...owner/package#dev-master vs.
owner/package#7.x-2.x-dev. I don't think this will be a common issue.
Contributed modules would commonly depend on stable release versions, but
still, we should be aware of the posibility.

**Comment by maoberlehner** [comment]
I think warning is all we can do - at some point when we have a UI that lists dependencies, we can also visualize those conflicts but for now resolving them as good as we can and show a warning is the best we can do.

In case of two urls we should just use what comes last (or first? doesn't matter I think) - In my opinion there is no point in trying to parse URLs for version strings or something like that because it would be very hard to get reliable results. As you said - that should be an edge case.
