### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by hipnaba** [maoberlehnerdrupal/bower_manager#13]
As i said, I'm new to online collaboration, so I'm not to sure how to handle everything.

How do we divide the work? I don't mind doing anything, just not sure if you want to work on something specific. It would be bad if both of us worked on the same thing, no?

Do we discuss everything in separate issues? Do I create an issue for everything? For example, we talked about depending on composer_manager, should I make an issue out of it? Who assigns it to someone? Do we just assign ourselves if we want to work on something? 

What's the scope of the project? Merging bower.json files is the core functionality. Managing (installing, uninstalling, listing) packages is the optional part. So first we both focus on merging or each of us does his thing? I'm sorry I completely replaced your code :). You haven't commented on that, are you fine with things so far? 

Do we write tests? Honestly, I'm kinda new to Drupal development too, so not really sure how unit testing works here, but I'll look into it.

Do we move code to other files? Our .module file is going to get rather big, should we move code to includes/*.inc files? How do we include them? Is having include_once __DIR__ . '/includes/*.inc'; statements at the top of our .module file ok?

**Comment by maoberlehner** [comment]
About dividing work - currently I don't have that much time and I want to invest some time in other projects, so the next few days (maybe up to two weeks) I won't do to much on this project and you can work freely how much or little you wan't (but always feel free to ask for my assistance!). In the future we should assignee new tasks immediately so there is no confusion about who's task it is - but conceptual changes should always get discussed.

Discussion should happen in issues when possible, that way our thoughts are documented and tied to the actual task. But I guess we need some place like IRC / Slack or something like that to discuss more general things - what do you think? To self assignee tasks is not only allowed but very much appreciated (as long as conceptual changes get discussed) If you think something is better suited for me feel free to assignee an issue to me.

I'm fine with your "rewrite" of my code - my version did (and still does) exactly (and only) what I needed but the 2.x version will be much more usable for a much broader set of people (including myself) and I'm very happy with that direction.

About the scope of the project - I think we should focus on the core functionality to have something that we can push to get released on drupal.org - I think the best way is to use the 7.x-2.0 milestone to mark issues that are needed for the core functionality - I just created the 7.x-2.5 and 7.x-3.0 milestones for everything we want to include eventually but isn't needed to get something released on drupal.org

Tests would be really cool and are something that would help us to get released on drupal.org more quickly - but I'll have to admit my knowledge on that topic is very limited.

Fine tuning and moving things in .inc files is something we should definitely do at some point but could be something we do in our 7.x-2.5 "refactor" release but if you prefer to use .inc files in general and it helps you to get things done faster you can start using them now - it would improve the general maintainability I think.

**Comment by maoberlehner** [comment]
about heading forward - I think we should create issues for everything that is needed to finish 7.x-2.0 and split those issues between us two according to our resources and talents.
