### ISSUE TITLE
BowerPHP

### ISSUE THREAD

**Issue by hipnaba** [maoberlehnerdrupal/bower_manager#8]
If we want to run bower from Drupal we need [BowerPHP](http://bowerphp.org/). 

BowerPHP is basically a dev dependency since you don't need it in production. We can use Tiara Bower for the drush version. It pulls BowerPHP into it's own dir so it's not in Drupal, and you don't need node.js to use Bower. Actually I'd like to move the code to this module because my project isn't published and that means we can't download it with drush.

However, if we want to be able to run it from the admin interface, we need it in Drupal. So far I've come up with this.

If the [Libraries](https://www.drupal.org/project/libraries) module is installed we can declare BowerPHP as a library and warn if we can't find it. Let the user know he needs to download it and extract it to sites/all/libraries or wherever. But if we detect [Composer Manager](https://www.drupal.org/project/composer_manager) we also check the vendor dir and if we can't find it, warn the user he needs to run composer update or whatever.

If after all this we still can't use BowerPHP we just error out.

Also ... BowerPHP doesn't support the `prune` command. But `list` works, so we can find extraneous packages and just delete them manually.

**Comment by maoberlehner** [comment]
I think BowerPHP is a nice enhancement but I don't want it as a default - the users should be free to use a workflow that includes node.js (e.g. I use a gulp workflow that integrates bower)

So I'm absolutely for integrating it in this module but either as a submodule that can be enabled / disabled at will or there must be a configuration option to enable / disable it.

**Comment by hipnaba** [comment]
We can make it fully optional. If we detect it we add a 'Run bower install' button in the settings. After the user consolidates bower.jsons and we don't have BowerPHP we just tell him the file is generated and he needs to run bower.json somehow.

But do we want to have a list of installed packages? We can't get it without running bower somehow. Do we want to try running it with exec in case there's a node.js version installed?

**Comment by maoberlehner** [comment]
Then we should make only the "install" part optional if we need bowerPHP for core functionality.

What would you prefer - run the install step automatically (if enabled) or manually?

**Comment by maoberlehner** [comment]
About running with exec - I have no opinion on this - but I guess it isn't a high priority
