### ISSUE TITLE
README: Authors -> Contributors

### ISSUE THREAD

**Issue by maoberlehner** [maoberlehnerdrupal/bower_manager#9]
I created a new branch 7.x-2.x-dev and merged your feature branch - feel free to add yourself to the "Author" section of the readme (Should be renamed to "Authors" or "Contributors" ?) and please delete the feature branch if you no longer need it.

**Comment by hipnaba** [comment]
Where can I work now? On the 7.x-2.x-dev branch? Or I need to create a branch to work on?

**Comment by maoberlehner** [comment]
You can work on 7.x-2.x-dev - just use a feature branch for really big changes (like the merge was)
